@apiUrl = http://127.0.0.1:8080 

GET {{apiUrl}}/rooms

##get booking
GET {{apiUrl}}/bookings

##create new booking
POST {{apiUrl}}/bookings
Content-type: application/json
{
    "room_id": 1,
    "guest_id": 1,
    "datefrom": "2024-07-01",
    "dateto": "2024-07-10",
}